const MSG = {
  SIGNUP_SUCCESS: "Signup successfully...",
  LOGIN_SUCCESS: "Login successfully...",
  INSERT_SUCCESS: "Insert successfully...",
  UPDATE_SUCCESS: "Update successfully...",
  FOUND_SUCCESS: "Found successfully...",
  DELETE_SUCCESS: "Delete successfully...",
  UPLOAD_SUCCESS: "Upload successfully...",
  CREATE_SUCCESS: "Create successfully...",
  LOGOUT_SUCCESS: "Logout successfully...",
  PASSWORD_RESET_SUCCESS: "Password reset successfully..",

  EMAIL_ALREADY: "Email already in use.. !!",
  EMAIL_NOT_EXIST: "Email does not exist.. !!",
  CREDENTIAL_INVALID: "Invalid credentials.. !!",
  TOKEN_EMPTY: "Empty token, authorization denied.. !!",
  TOKEN_INVALID: "Invalid token, authorization denied.. !!",
  EXTENSION_INVALID: "Invalid extension.. !!",
  FIELD_REQUIRED: "Field is required.. !!",
  NOT_FOUND: "Not found.. !!",

  FEEDBACK_SENT_SUCCESS: "Feedback sent successfully ...",

  SUCCESS: "Success ...",
  SUCCESSFULLY: "Successfully ...",
  LIKE_SUCCESS: "Like successfully...",
  UNLIKE_SUCCESS: "Unlike successfully...",
  LIKE_ALREADY: "Already liked.. !!",
  UNLIKE_ALREADY: "Has not yet been liked.. !!",
  LOGIN_REQUIRED: "Please, login first to continue.. !!",
  FOLLOW_SUCCESS: "Follow successfully...",
  UNFOLLOW_SUCCESS: "Unfollow successfully...",
  FOLLOW_ALREADY: "Already followed.. !!",
  UNFOLLOW_ALREADY: "You have not yet been followed",
  SERVER_ERROR: "Server error.. !!",
  PASSWORD_SEND_SUCCESS: "New password sent to your email..",
  PASSWORD_DIFFERENT: "Password and confirm password must be the same.. !!",

  OTP_SEND: "OTP sent successfully..",
  OTP_UNSEND: "OTP not sent.. !!",
  OTP_RESEND: "OTP resent successfully..",
  OTP_VERIFIED_SUCCESS: "OTP verified successfully..",
  OTP_INVALID: "Invalid OTP.. !!",
  OTP_UNVERIFIED: "Please, first verify OTP.. !!",
};

module.exports = MSG;
